# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.2
  - 5.3
  - 5.4

script: phpunit --configuration .travis_phpunit.xml --coverage-text

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sudo touch /usr/local/bin/cap
  - sudo chmod +x /usr/local/bin/cap
  - chmod src/main/sh/installsmarty.sh
  - ./src/main/sh/installsmarty.sh
  - chmod src/main/sh/installmailchimp.sh
  - ./src/main/sh/installmailchimp.sh

services: mongodb

notifications:
  webhooks: http://requestb.in/1inunuo1

branches:
  only:
    - develop
#    - master
