# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
#  - 5.2
  - 5.3
  - 5.4

script: phpunit --configuration .travis_phpunit.xml --coverage-text

before_script:
#  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - sudo touch /usr/local/bin/cap
  - sudo chmod +x /usr/local/bin/cap
  - sudo chmod +x src/main/sh/install*.sh
  - sudo chmod +x src/main/sh/mongo.sh
  - ./src/main/sh/mongo.sh ext/data/welcomegift.json
  - ./src/main/sh/installsmarty.sh
  - ./src/main/sh/installmailchimp.sh
  - ./src/main/sh/installswift.sh
  - ./src/main/sh/installjasmine.sh
  - ./src/main/sh/installgoogleapi.sh
  - ./src/main/sh/installmaxmind.sh
  - mv ./src/main/php/WTConfig.example.php ./src/main/php/WTConfig.php

services: mongodb

notifications:
  webhooks: http://requestb.in/1inunuo1

branches:
  only:
    - develop
    - master

