# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php
php:
  - 5.2
  - 5.3
  - 5.4

script: phpunit --configuration .travis_phpunit.xml

notifications:
  webhooks: http://requestb.in/1inunuo1

branches:
  only:
    - develop
#    - master
