<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-01 at 01:16:06.
 */
class FanProfileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FanProfile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FanProfile("webhat");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
				$mongo = new Mongo(); // connect
				$config = new WTConfig();
				$db = $mongo->selectDB($config->wtdatabase);
				$db->profiles->drop();
    }

    /**
     * @covers FanProfile::setFanFirstName
     * @todo   Implement testSetFanFirstName().
     */
    public function testSetFanFirstName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FanProfile::setFanLastName
     * @todo   Implement testSetFanLastName().
     */
    public function testSetFanLastName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FanProfile::addPayment
     * @todo   Implement testAddPayment().
     */
    public function testAddPayment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
