<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-01 at 01:14:11.
 */
class WTConfigTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var WTConfig
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new WTConfig;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
